### ISSUE TITLE
How often do you push builds to npm?

### ISSUE THREAD

**Issue by snowgears** [baianat/vuse#10]
Hello again! I just had a quick question.

I noticed there is the ability to drag and drop sections from the sidebar into the main page on the example site but when I use the build thats installed via npm (listed as version 0.0.0 by the way), there is no ability for that which I can see.

Thanks in advance!

**Comment by Abdelrahman3D** [comment]
I believe, I'm going to release a new version very soon w/ drag-n-drop feature and solving performance issues, thank you for your interest. 😃

**Comment by snowgears** [comment]
Thank you for the info! I've never registered a project with NPM so I wasn't sure if it was supposed to be auto-building from a repo or if you had to actually submit new builds. Thanks!
