### ISSUE TITLE
Plugin not working as used in documentation [Help wanted!]

### ISSUE THREAD

**Issue by ErenYatkin** [baianat/vuse#24]
Hello, I found you section builder and it has really cool features. I followed instructions as mentioned in the installation part on the document but I could not get it work in my vue application.

App.vue
```
<template>
  <div id="app">
    <b-builder />
  </div>
</template>
```

main.js
```
import Vue from 'vue'
import Builder from 'vuse';
import App from './App.vue'

Vue.config.productionTip = false

Vue.use(Builder, {});

new Vue({
  render: h => h(App),
}).$mount('#app')
```

Error
```
 Unknown custom element: <b-builder> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <App>
       <Root>```

**Comment by Abdelrahman3D** [comment]
Hello, it looks like that the documentation is outdated, can you please replace `b-builder` with `vuse-builder`, and tell me if it worked for you, sorry for inconvenient.

**Comment by ErenYatkin** [comment]
Hey, I replaced the tag with `vuse-builder` but styles did not loaded as you can see in the screen shot, any ideas ?
<img width="1095" alt="Screen Shot 2019-03-16 at 12 15 07" src="https://user-images.githubusercontent.com/8920659/54473182-5d4e3480-47e5-11e9-8ced-0204861c2572.png">

**Comment by Abdelrahman3D** [comment]
Sure we will add it, thank you!
