### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [baianat/vuse#29]
Hi...
Just saw your fantastic project and for me, the idea of the project is really amazing... I am a logo/Icon designer and I want to help give my Free contribution to your project by creating a Logo/Icon for your project, as part of my love and passion to always help contribute to great Open Source projects...

Currently working on an idea concept, and I will share it here once I complete it, for you to give me your feedback or suggestion on any changes you might want to satisfy your needs.

Your response would be greatly appreciated...
Regards!

**Comment by logaretm** [comment]
WOW, I really appreciate you taking interest in this library. I would love to use your logo for this library and you will be fully credited.

Can't wait for it, thanks!

**Comment by chimzycash** [comment]
I really appreciate your quick response... Would finish up the idea concept and share it here for your feedback.

**Comment by chimzycash** [comment]
Hi... Here is the idea concept for the logo design...

![LOGO DESIGN_Vuse_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/61177712-78825280-a5d3-11e9-9a61-93068cbe5afe.jpg)
![LOGO DESIGN_Vuse_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/61177713-791ae900-a5d3-11e9-9fa1-764d440dd24e.jpg)
![LOGO DESIGN_Vuse_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/61177714-791ae900-a5d3-11e9-9b9b-c970fa0acd04.jpg)
![LOGO DESIGN_Vuse_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/61177715-79b37f80-a5d3-11e9-8067-090fffbdb667.jpg)
![LOGO DESIGN_Vuse_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/61177716-79b37f80-a5d3-11e9-9c5a-b91d1f132e6a.jpg)
![LOGO DESIGN_Vuse_BACKGROUND_5b](https://user-images.githubusercontent.com/37814297/61177717-7a4c1600-a5d3-11e9-8ac9-2952fbe1e4a8.jpg)
![LOGO DESIGN_Vuse_idea concept_NEW](https://user-images.githubusercontent.com/37814297/61177720-7ae4ac80-a5d3-11e9-8e44-a783c677999a.jpg)

**Comment by logaretm** [comment]
That looks amazing, The concept of element stacking is very clever, I like the purple gradient as well. I can place it immediately if that is okay with you and like I said you will be fully credited.

Let me know if you can send me the assets or you can PR it if you would like.

**Comment by chimzycash** [comment]
Glad that you like the design... Feel free to place it

Would prepare all the logo files and create a PR

**Comment by logaretm** [comment]
I added your logo on both the docs and the readme. Let me know if need any adjustments.

**Comment by chimzycash** [comment]
Here is the Google drive link containing all the logo files including the vector files.
https://drive.google.com/drive/folders/1UtQ39mjLPmycWMbiYI6Jk6Pqe4EsMf-0?usp=sharing
